### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [thiezn/awsaccountmgr#5]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.0.9. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary awsaccountmgr -w /tmp/ext awsaccountmgr==0.0.9
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting awsaccountmgr==0.0.9
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/57b/3def90302676e/awsaccountmgr-0.0.9.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-fxwkvxbn/awsaccountmgr/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-fxwkvxbn/awsaccountmgr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-fxwkvxbn/awsaccountmgr/pip-egg-info
         cwd: /tmp/pip-wheel-fxwkvxbn/awsaccountmgr/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-fxwkvxbn/awsaccountmgr/setup.py", line 8, in <module>
        with open('HISTORY.md', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thiezn** [comment]
Hi @thatch thanks for that! I didn't realize this would happen. I read up on it [here](https://packaging.python.org/guides/using-manifest-in/) and have included a MANIFEST.in in the latest commit, to explicitly include HISTORY.md and README.md.

Thanks and let me know if its still giving you issues.
